// Code generated by protoc-gen-mcp. DO NOT EDIT.
// versions:
//  - protoc-gen-mcp {{ .PluginVersion }}
//  - protoc         TODO
// source: TODO

package {{ .GoPackageName }}

import (
    {{ if .Tools }}"context"
    {{ end }}
    "github.com/mark3labs/mcp-go/server"
    {{ if .Tools }}"github.com/mark3labs/mcp-go/mcp"{{ end }}
)

func New{{.Name}}MCPServer(client {{ .Name }}Client) *server.MCPServer {
    s := server.NewMCPServer(
        "{{ .Name }}",
        "{{ .Version }}",
    )

    {{ range .Tools }}
    {{ .Name }}Tool := mcp.NewTool("{{ .Name }}",
        {{ if .Description }}mcp.WithDescription("{{ .Description }}"),{{ end }}
    )
    s.AddTool({{ .Name }}Tool, func(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
        return nil, nil
    })
    {{ end }}

   return s
}
