// Code generated by protoc-gen-go-mcp. DO NOT EDIT.
// versions:
//  - protoc-gen-go-mcp {{ .PluginVersion }}
//  - protoc         {{ .ProtocVersion }}
// source: {{ .SourcePath }}

package {{ .GoPackageName }}

import (
    "context"
    "github.com/mark3labs/mcp-go/server"
    "github.com/mark3labs/mcp-go/mcp"
    "google.golang.org/protobuf/encoding/protojson"
)

{{ range $service := .Services }}
// TODO
{{ end }}
