// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protos/extension.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MCPServiceOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPServiceOption) Reset() {
	*x = MCPServiceOption{}
	mi := &file_protos_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPServiceOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPServiceOption) ProtoMessage() {}

func (x *MCPServiceOption) ProtoReflect() protoreflect.Message {
	mi := &file_protos_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPServiceOption.ProtoReflect.Descriptor instead.
func (*MCPServiceOption) Descriptor() ([]byte, []int) {
	return file_protos_extension_proto_rawDescGZIP(), []int{0}
}

func (x *MCPServiceOption) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type MCPMethodOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPMethodOption) Reset() {
	*x = MCPMethodOption{}
	mi := &file_protos_extension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPMethodOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPMethodOption) ProtoMessage() {}

func (x *MCPMethodOption) ProtoReflect() protoreflect.Message {
	mi := &file_protos_extension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPMethodOption.ProtoReflect.Descriptor instead.
func (*MCPMethodOption) Descriptor() ([]byte, []int) {
	return file_protos_extension_proto_rawDescGZIP(), []int{1}
}

var file_protos_extension_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*MCPServiceOption)(nil),
		Field:         1000,
		Name:          "mcp.server",
		Tag:           "bytes,1000,opt,name=server",
		Filename:      "protos/extension.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MCPMethodOption)(nil),
		Field:         1000,
		Name:          "mcp.method",
		Tag:           "bytes,1000,opt,name=method",
		Filename:      "protos/extension.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional mcp.MCPServiceOption server = 1000;
	E_Server = &file_protos_extension_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional mcp.MCPMethodOption method = 1000;
	E_Method = &file_protos_extension_proto_extTypes[1]
)

var File_protos_extension_proto protoreflect.FileDescriptor

const file_protos_extension_proto_rawDesc = "" +
	"\n" +
	"\x16protos/extension.proto\x12\x03mcp\x1a google/protobuf/descriptor.proto\",\n" +
	"\x10MCPServiceOption\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x11\n" +
	"\x0fMCPMethodOption:O\n" +
	"\x06server\x12\x1f.google.protobuf.ServiceOptions\x18\xe8\a \x01(\v2\x15.mcp.MCPServiceOptionR\x06server:M\n" +
	"\x06method\x12\x1e.google.protobuf.MethodOptions\x18\xe8\a \x01(\v2\x14.mcp.MCPMethodOptionR\x06methodB\rZ\vinternal/pbb\x06proto3"

var (
	file_protos_extension_proto_rawDescOnce sync.Once
	file_protos_extension_proto_rawDescData []byte
)

func file_protos_extension_proto_rawDescGZIP() []byte {
	file_protos_extension_proto_rawDescOnce.Do(func() {
		file_protos_extension_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_extension_proto_rawDesc), len(file_protos_extension_proto_rawDesc)))
	})
	return file_protos_extension_proto_rawDescData
}

var file_protos_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_extension_proto_goTypes = []any{
	(*MCPServiceOption)(nil),            // 0: mcp.MCPServiceOption
	(*MCPMethodOption)(nil),             // 1: mcp.MCPMethodOption
	(*descriptorpb.ServiceOptions)(nil), // 2: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 3: google.protobuf.MethodOptions
}
var file_protos_extension_proto_depIdxs = []int32{
	2, // 0: mcp.server:extendee -> google.protobuf.ServiceOptions
	3, // 1: mcp.method:extendee -> google.protobuf.MethodOptions
	0, // 2: mcp.server:type_name -> mcp.MCPServiceOption
	1, // 3: mcp.method:type_name -> mcp.MCPMethodOption
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_extension_proto_init() }
func file_protos_extension_proto_init() {
	if File_protos_extension_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_extension_proto_rawDesc), len(file_protos_extension_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_protos_extension_proto_goTypes,
		DependencyIndexes: file_protos_extension_proto_depIdxs,
		MessageInfos:      file_protos_extension_proto_msgTypes,
		ExtensionInfos:    file_protos_extension_proto_extTypes,
	}.Build()
	File_protos_extension_proto = out.File
	file_protos_extension_proto_goTypes = nil
	file_protos_extension_proto_depIdxs = nil
}
