# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenGoMcp < Formula
  desc ""
  homepage ""
  version "0.1.0"

  depends_on "mkcert" => "1.4.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juliendoutre/protoc-gen-go-mcp/releases/download/v0.1.0/protoc-gen-go-mcp_Darwin_x86_64.tar.gz"
      sha256 "d8231412e2a63e6a5196232dd67a3e787ff49aa3efb5015ff8f6f57fb17d2c8e"

      def install
        bin.install "protoc-gen-go-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juliendoutre/protoc-gen-go-mcp/releases/download/v0.1.0/protoc-gen-go-mcp_Darwin_arm64.tar.gz"
      sha256 "14d468dd464259bc6de29cb04d5d19b0ab4cf939cf2e5be419084bca2d57c3b0"

      def install
        bin.install "protoc-gen-go-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/protoc-gen-go-mcp/releases/download/v0.1.0/protoc-gen-go-mcp_Linux_x86_64.tar.gz"
        sha256 "c6d21f6836f7497361441cda8ee743540763e4fe5b8dfeb5bdb5f6bd86e02f00"

        def install
          bin.install "protoc-gen-go-mcp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/juliendoutre/protoc-gen-go-mcp/releases/download/v0.1.0/protoc-gen-go-mcp_Linux_arm64.tar.gz"
        sha256 "48d9a806e151754b30c4fc5b057f065474306911f261c47628c2feb6dcb59f68"

        def install
          bin.install "protoc-gen-go-mcp"
        end
      end
    end
  end
end
