// Code generated by protoc-gen-mcp. DO NOT EDIT.
// versions:
//  - protoc-gen-mcp unknown
//  - protoc         TODO
// source: TODO

package pb

import (
	"context"

	"github.com/mark3labs/mcp-go/server"
	"github.com/mark3labs/mcp-go/mcp"
)

func NewHelloWorldMCPServer(client HelloWorldClient) *server.MCPServer {
	s := server.NewMCPServer(
		"HelloWorld",
		"1.0.0",
	)

	GreetTool := mcp.NewTool("Greet",
		mcp.WithDescription("Say hi!"),
	)
	s.AddTool(GreetTool, func(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		return nil, nil
	})

	return s
}
