// Code generated by protoc-gen-mcp. DO NOT EDIT.
// versions:
//  - protoc-gen-mcp unknown
//  - protoc         TODO
// source: TODO

package pb

import (
	"context"

	"github.com/mark3labs/mcp-go/server"
	"github.com/mark3labs/mcp-go/mcp"
	"google.golang.org/protobuf/encoding/protojson"
)

func NewHelloWorldMCPServer(client HelloWorldClient) *server.MCPServer {
	s := server.NewMCPServer(
		"HelloWorld",
		"1.0.0",
	)

	GreetTool := mcp.NewTool("Greet",
		mcp.WithDescription("Say hi!"),
	)
	s.AddTool(GreetTool, func(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		in := &GreetRequest{}

		out, err := client.Greet(ctx, in)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		return mcp.NewToolResultText(protojson.Format(out)), nil
	})

	return s
}
