// Code generated by protoc-gen-go-mcp. DO NOT EDIT.
// versions:
//  - protoc-gen-go-mcp (unknown)
//  - protoc         v5.29.3
// source: example/api.proto

package pb

import (
	"context"
	"github.com/mark3labs/mcp-go/server"
	"github.com/mark3labs/mcp-go/mcp"
	"google.golang.org/protobuf/encoding/protojson"
)

// TODO
