// Code generated by protoc-gen-go-random. DO NOT EDIT.
// versions:
//  - protoc-gen-go-random 0.3.0
//  - protoc         v5.29.3
// source: example/api.proto

package pb

import (
	"context"
	"math/rand"
	"testing/quick"
	"reflect"
)

type HelloWorldRandomServer struct {
	UnimplementedHelloWorldServer
	Rand *rand.Rand
}

func (r *HelloWorldRandomServer) Greet(ctx context.Context, _ *GreetRequest) (*GreetResponse, error) {
	out := &GreetResponse{}

	randValue(&out.Greeting, r.Rand)

	return out, nil
}

func randValue[T any](out *T, r *rand.Rand) {
	v, _ := quick.Value(reflect.ValueOf(*out).Type(), r)
	*out = v.Interface().(T)
}
